name = "telegram-shop"
pages_build_output_dir = "out"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_MERCHANT_URL = "https://merchant.thecong2610.workers.dev"
