name = "printerval"
main = ".open-next/worker.js" 
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXTJS_ENV = "production"
# Trỏ về Backend Merchant của bạn
NEXT_PUBLIC_MEDUSA_BACKEND_URL = "https://merchant.thecong2610.workers.dev"

[observability]
enabled = true