export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const dynamic = 'force-dynamic';

import { Providers } from './providers';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
